tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"

brew "zsh"
brew "git"
brew "tree"
brew "tig"
brew "n"
brew "fzf"
brew "ripgrep"
brew "ag"
brew "direnv"
brew "tmux"
brew "peco"
brew "python3"
brew "skaffold"
brew "nvim"
brew "kubernetes-cli"
brew "kustomize"
brew "minikube"
brew "reattach-to-user-namespace"
brew "rust"
brew "watch"
brew "stern"
# eksctl
tap "weaveworks/tap"
brew "weaveworks/tap/eksctl"

cask "alacritty"
cask "alfred"
cask "amazon-music"
cask "android-studio"
cask "microsoft-teams"
cask "viber"
cask "visual-studio-code"
cask "rambox"
cask "google-chrome-canary"
cask "google-japanese-ime"
cask "ngrok"
cask "karabiner-elements"
cask "skitch"
cask "postman"
cask "bettertouchtool"
cask "docker"
cask "virtualbox"
cask "firefox"
cask "sketch"
# font
tap "homebrew/cask-fonts"
cask "font-noto-nerd-font"
cask "kobo"

# mas "LINE", id: 539883307
# mas "Xcode", id: 497799835

