-- keymap
vim.api.nvim_set_var("mapleader", " ")
vim.api.nvim_set_var("maplocalleader", ";")
vim.api.nvim_set_keymap("n", "<C-p>", '"0p', { noremap = true })
vim.api.nvim_set_keymap("v", "<C-p>", '"0p', { noremap = true })
vim.keymap.set("n", "<leader>h", ":%s///<left><left>")
vim.keymap.set("n", "<C-h>", "<C-W>h")
vim.keymap.set("n", "<C-j>", "<C-W>j")
vim.keymap.set("n", "<C-k>", "<C-W>k")
vim.keymap.set("n", "<C-l>", "<C-W>l")
vim.keymap.set("n", "ge", vim.diagnostic.open_float, { desc = "Show diagnostic" })
vim.keymap.set("n", "<leader>n", ":bn<CR>", { desc = "Next buffer" })
vim.keymap.set("n", "<leader>p", ":bp<CR>", { desc = "Previous buffer" })
vim.keymap.set("n", "<leader>q", ":bd<CR>", { desc = "Delete buffer" })
